apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phr-controller
  template:
    metadata:
      labels:
        app: phr-controller
    spec:
      serviceAccountName: phr-controller
      containers:
        - name: controller
          image: ghcr.io/yoramvandevelde/phr:0.1.5
          env:
            - name: PIHOLE_URL
              value: "http://10.10.20.53"
            - name: PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phr-pihole
                  key: password
