apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phr-controller
  template:
    metadata:
      labels:
        app: phr-controller
    spec:
      serviceAccountName: phr-controller
      containers:
        - name: controller
          image: ghcr.io/yoramvandevelde/phr:0.1.7
          imagePullPolicy: Always
          env:
            - name: PIHOLE_URL
              value: "http://10.20.30.40"
            - name: PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phr-pihole
                  key: password
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
